services:
  wallet_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/workspace/src/app
      - PORT=8000
    env_file:
      - .env
    depends_on:
      - postgres
      
  redis:
    image: "redis:latest" 
    container_name: redis_container 
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data 
  
  postgres:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  redis_data:
  postgres_data:
